### ISSUE TITLE
Tricks disable saber collision vibrations.

### ISSUE THREAD

**Issue by danyev3** [Fernthedev/Quest-Trick-Saber#1]
(0.3.1)
Spinning the sabers disables the vibrations when you collide the sabers, but doesn't enable them again when you stop spinning. Throwing them takes a little bit but also ends up disabling vibrations permanently.
Only way to fix it is to restart the game, it got fixed randomly once but I couldn't reproduce it consistently.

**Comment by Fernthedev** [comment]
Fixed in 9df657ec0106f8432a858e0b31f858639286c150
