### ISSUE TITLE
I found a bug and how to recreate it 

### ISSUE THREAD

**Issue by Rlasco25yt** [Fernthedev/Quest-Trick-Saber#10]
the bug is the sabers freeze the wrong way so they can be backwards etc. Idk if anyone has found this but to do it spin and throw the sabers at the same time and bring them back and they are frozen to fix you just spin them again

**Comment by Fernthedev** [comment]
This is a known bug and there won't really be a fix to it since it's low priority. I'm not a big fan of it but it's not very straight forward to fix 😅
