### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by tricksaberissexy** [Fernthedev/Quest-Trick-Saber#13]
Hi, so I am a member of the BSMG Discord server and was trying out you're new TrickSaber mod and the functions are great (I love spinning the sabers)! The only problem is that whenever I go back to the menu, fail a level, or complete a level the whole game crashes. No discredit to you or the other modders, you are all amazing people. Thanks!

**Comment by Fernthedev** [comment]
Fixed in 8015450059ac81550ba256f36835e0bc6dd1b361
