### ISSUE TITLE
Symbol not located

### ISSUE THREAD

**Issue by sharpshadow23** [Fernthedev/Quest-Trick-Saber#5]
I'm trying to use Trick Saber on the Oculus Quest. I have mod list installed and I see that when I hover over this mod, it's the only one that fails to load. It fails to load because it cannot locate a symbol. Does this mean my sabers aren't supported? I am using the default sabers.

**Comment by gabewil** [comment]
did you fix it? having same issue

EDIT: For anyone else having this issue, be sure your questUI is toggled on, or try toggling it off and on again.
