### ISSUE TITLE
sabers not doing tricks

### ISSUE THREAD

**Issue by Litten152** [Fernthedev/Quest-Trick-Saber#8]
when I do the things that it say to do the tricks it does nothing and I wonder if I need a different mod on or not for this to work.

**Comment by LyonelYu** [comment]
same problem but only with the spinning. the throwing works normaly at my quest2 but no spinning.

**Comment by LyonelYu** [comment]
i got it now working on my quest2. I just deleted the mod and reinstaled it and now it works.
